apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datastore-be
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aasha9kolukulapally-rgb/Kubernetes.git
    targetRevision: main
    path: Kubernetes/datastore-be   # ⚠️ adjust if needed

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
